version: "3.9"
services:
    docs-api:
      container_name: docs-api
      # Crea la imagen con el archivo Dockerfile de esta misma carpeta
      image: docs-img:1.0
      restart: always
      volumes:
        - ./app:/home/jonnattan/app
      ports:
        - "8080:8080"
      env_file:
        - ../file_docs.env
      networks:
        - db-net
networks:
  db-net:
