version: '3.9'
services:
    docs-api:
      container_name: docs-api-dev
      image: docs-img:dev
      volumes:
        - ./app:/src/app
      ports:
        - "8081:8081"
      env_file:
        - ../file_docs.env
      networks:
        - net
      command: tail -f /src/requirements.txt

networks:
  net:
