FROM python:3.14-rc-slim

LABEL VERSION=1.0
LABEL DESCRIPCION="API para documentos"

ENV TZ 'UTC'
ENV HOST_BD ''
ENV USER_BD ''
ENV PASS_BD ''
ENV SERVER_API_KEY ''
ENV AES_KEY ''
ENV FLASK_APP app
ENV FLASK_DEBUG development

WORKDIR /src

COPY requirements.txt /src/requirements.txt

RUN apt-get update -y && \
    apt-get install -y build-essential && \
    apt-get install -y libssl-dev && \
    apt-get install -y libffi-dev && \
    apt-get install -y python3-dev && \
    apt-get install -y cargo

EXPOSE 8080

CMD [ "python", "http-server.py", "8080"]
    