services:
    docs-api:
      container_name: docs-api
      image: jonnattangc/docsservice:1.0.0
      #build:
      #  context: .
      #  dockerfile: Dockerfile
      #restart: always
      #volumes:
      #  - ./app:/home/jonnattan/app
      #  - ../envs/credential-logia.json:/home/jonnattan/app/credential-logia.json
      ports:
        - "8095:8095"
      env_file:
        - ../envs/docs.env
      networks:
        - db-net
      #command: tail -f /home/jonnattan/app/main.py
networks:
  db-net:
